bookManagement/bookManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('management.urls')) # 配置app的url
]

# 此处静态文件的url只有当settings里的DEBUG为True时才生效
if settings.DEBUG:
    # 做一次其它url的映射
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookManagement/management/urls.py
'''
URL为该系统的访问入口
设计URL模型对URL地址表达式和python视图处理函数间进行映射

细明：
    主页  注册  登录  注销  修改密码    添加书籍（管理员）   添加照片（管理员）   书籍细明
'''
from django.urls import path, re_path
from management import views

urlpatterns = [
    # (字符串， 调用视图函数， url-name)
    path('', views.index, name='homepage'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('change_password/', views.change_password, name='change_password'),
    path('add_book/', views.add_book, name='add_book'),
    path('add_img/', views.add_img, name='add_img'),
    path('log/', views.log, name='log'),
    path('add_intro/',views.add_intro,name='add_intro'),
    # /<路径转换>/
    path('book_list/<str:category>/', views.book_list, name='book_list'),
    path('book_detail/<int:book_id>/comments/', views.view_comments, name='view_comments'),
    re_path(r'^book_detail/(?P<book_id>[0-9]+)/$', views.book_detail, name='book_detail'),
]

bookManagement/management/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Book(models.Model):
    name = models.CharField(max_length=128, verbose_name='书籍名称')
    author = models.CharField(max_length=64, verbose_name='作者')
    price = models.FloatField(default=.0, verbose_name='定价')
    publish_date = models.DateField(null=True, blank=True, verbose_name='出版日期')
    category = models.CharField(max_length=32, default='未分类', verbose_name='书籍分类')
    create_datetime = models.DateTimeField(auto_now_add=True, verbose_name='添加日期')

    def __str__(self):
        return self.name

class Image(models.Model):
    name = models.CharField(max_length=128, verbose_name='图片名称')
    description = models.TextField(default='', verbose_name='图片描述')
    img = models.ImageField(upload_to='image/%Y/%m/%d/', verbose_name='图片')
    book = models.ForeignKey(Book, on_delete=models.CASCADE, verbose_name='所属书籍')

    def __str__(self):
        return self.name

# class Review(models.Model):
#     book = models.ForeignKey(Book, on_delete=models.CASCADE, verbose_name='书籍')
#     user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='用户')
#     review_text = models.TextField(verbose_name='评论内容')
#     review_date = models.DateTimeField(auto_now_add=True, verbose_name='评论日期')
#
#     def __str__(self):
#         return f"{self.user.username} - {self.book.name}"
#
# class Score(models.Model):
#     book = models.ForeignKey(Book, on_delete=models.CASCADE, verbose_name='书籍')
#     user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='用户')
#     score_value = models.PositiveSmallIntegerField(verbose_name='评分值', choices=[(i, i) for i in range(1, 6)])
#     score_date = models.DateTimeField(auto_now_add=True, verbose_name='评分日期')
#
#     def __str__(self):
#         return f"{self.user.username} - {self.book.name} ({self.score_value})"


class Intro(models.Model):
    introduction = models.TextField(default='', verbose_name='书籍简介')
    book = models.ForeignKey(Book, on_delete=models.CASCADE, verbose_name='所属书籍')
    #created_at = models.DateTimeField(auto_now_add=True)  # 时间戳字段

    def __str__(self):
        return f"{self.book.name} - Intro"

class Comment(models.Model):
    book = models.ForeignKey(Book, related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)  # 关联到用户
    content = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    rating = models.IntegerField(
        choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')])

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f'Comment by {self.book.name}'

    def get_rating_range(self):
        return range(self.rating)

bookManagement/management/views.py
from django.shortcuts import render, reverse,redirect
from django.http import HttpResponseRedirect
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib import auth
from django.contrib.auth.decorators import login_required, user_passes_test
from .models import Book, Image,Intro,Comment
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
import re
from django.db.models import Avg

# Create your views here.
'''
    主页视图
'''
def index(request):
    user = request.user if request.user.is_authenticated else None
    context = {
        'active_menu': 'homepage',
        'user': user,
    }
    return render(request, 'management/index.html', context)

# 用户模型
# -------------------------------------------------------------------------------------------------
'''
    对用户状态进行判断，如果已经登录就跳转首页，反之注册
    # 添加了对method请求方法的处理形式：
        如：用户通过post方式提交表单时产生哈希形式的文件，而某些较复杂情况会产生json文件（该项目暂不考虑此情况）
'''
def sign_up(request):
    if request.user.is_authenticated: # 判断是否登录
        return HttpResponseRedirect(reverse('homepage'))
    # context = {
    #     'active_menu': 'homepage',
    #     'user': None
    # }
    # return render(request, 'management/sign_up.html', context)
    state = None # 用于描述注册的状态
    if request.method == 'POST': #判断post
        # 联立sign_up.html中的require
        password = request.POST.get('password', '')
        repeat_password = request.POST.get('repeat_password', '')

        ret = re.match("(?!^[_#@]+$)(?!^[_/,\;#]).{8,12}", password)

        if password == '' or repeat_password == '':
            state = 'empty'
        elif len(password) > 12:
            state = 'out_of_range'
        elif not ret:
            state = 'grammar_error'
        elif password != repeat_password:
            state = 'repeat_error'
        else:
            username = request.POST.get('username', '')
            if User.objects.filter(username=username):
                state = 'user_exist'
            else:
                new_user = User.objects.create_user(username=username, password=password,\
                                                    email=request.POST.get('email', ''))
                new_user.save()
                state = 'success'
    context = {
        'active_menu': 'homepage',
        'state': state,
        'user': None,
    }
    return render(request, 'management/sign_up.html', context)

'''
    登陆界面：
        实施了对state的标注等
'''
def login(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('homepage'))
    state = None
    if request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            target_url = request.POST.get('next', reverse('homepage')) # 获取next
            return HttpResponseRedirect(target_url)
        else:
            state = 'not_exist_or_password_error'
    context = {
        'active_menu': 'homepage',
        'state': state,
        'user': None,
    }
    return render(request, 'management/login.html', context)

'''
注销：
    对于注销就不需要创建单独的页面，设置一个块直接返回指定页面即可
'''
def logout(request):
    # respons = HttpResponseRedirect(reverse('homepage'))
    # respons.delete_cookie('name')
    # del request.session['username']
    auth.logout(request)
    return HttpResponseRedirect(reverse('homepage'))


'''
修改密码：
    与之前不同的是，添加了@login_required # 告诉程序，使用这个方法是要求用户登录的
    这是一个很多开发者关心的问题：
        服务页面是需要登录后才能访问的，给所有的视图函数都加上is_authenticated进行判断无疑是较高冗余的
        @login_required完美解决了这个问题
'''
@login_required
def change_password(request):
    user = request.user
    state = None
    if request.method == 'POST':
        old_password = request.POST.get('old_password', '')
        new_password = request.POST.get('new_password', '')
        repeat_password = request.POST.get('repeat_password', '')

        ret = re.match("(?!^[_#@]+$)(?!^[_/,\;#]).{8,12}", new_password)

        if user.check_password(old_password):
            if not new_password:
                state = 'empty'
            elif len(new_password) > 12:
                state = 'out_of_range'
            elif not ret:
                state = 'grammar_error'
            elif new_password != repeat_password:
                state = 'repeat_error'
            else:
                user.set_password(new_password)
                user.save()
                state = 'success'
        else:
            state = 'password_error'
    content = {
        'user': user,
        'active_menu': 'homepage',
        'state': state,
    }
    return render(request, 'management/change_password.html', content)
# -------------------------------------------------------------------------------------------------


# 图书模型
# -------------------------------------------------------------------------------------------------
'''
添加图书：
    类似于上述的修改密码视图，添加了一个判断权限的修饰器
'''
@user_passes_test(lambda u: u.is_staff)
def add_book(request):
    user = request.user
    state = None
    if request.method == 'POST':
        new_book = Book(
            name = request.POST.get('name', ''),
            author = request.POST.get('author', ''),
            category = request.POST.get('category', ''),
            price = request.POST.get('price', ''),
            publish_date = request.POST.get('publish_date', ''),
        )
        new_book.save()
        state = 'success'
    context = {
        'user': user,
        'active_menu': 'add_book',
        'state': state,
    }
    return render(request, 'management/add_book.html', context)

'''
图片上传:
    明细：
        要为具体的一本书上传图片，所以需要将图书列表也一起传递到前端
'''
@user_passes_test(lambda u: u.is_staff)
def add_img(request):
    user = request.user
    state = None
    if request.method == 'POST':
        try:
            new_img = Image(
                name=request.POST.get('name', ''),
                description=request.POST.get('description', ''),
                img=request.FILES.get('img', ''), # 上传的文件被保存在FILES中
                book=Book.objects.get(pk=request.POST.get('book', ''))
            )
            new_img.save()
        except Book.DoesNotExist as e:
            state = 'error'
            print(e)
        else:
            state = 'success'
    context = {
        'user': user,
        'state': state,
        'book_list': Book.objects.all(),
        'active_menu': 'add_img',
    }
    return render(request, 'management/add_img.html', context)

@user_passes_test(lambda u: u.is_staff)
def add_intro(request):
    user = request.user
    state = None
    if request.method == 'POST':
        book = Book.objects.get(pk=request.POST.get('book', ''))
        Intro.objects.filter(book=book).delete()
        try:
            new_intro = Intro(
                introduction=request.POST.get('introduction', ''),
                #img=request.FILES.get('img', ''), # 上传的文件被保存在FILES中
                book=book
            )
            new_intro.save()
        except Book.DoesNotExist as e:
            state = 'error'
            print(e)
        else:
            state = 'success'
    context = {
        'user': user,
        'state': state,
        'book_list': Book.objects.all(),
        'active_menu': 'add_intro',
    }
    return render(request, 'management/add_intro.html', context)


'''
图书列表：
    分页
'''
@login_required
def book_list(request, category='all'):
    user = request.user
    category_list = Book.objects.values_list('category', flat=True).distinct() # 去重
    if Book.objects.filter(category=category).count() == 0:
        category = 'all'
        books = Book.objects.all()
    else:
        books = Book.objects.filter(category=category)

    paginator = Paginator(books, 5) # 每页5个对象
    page = request.GET.get('page')
    try:
        books = paginator.page(page)
    except PageNotAnInteger:
        books = paginator.page(1)
    except EmptyPage:
        books = paginator.page(paginator.num_pages)

    context = {
        'user': user,
        'active_menu': 'view_book',
        'category_list': category_list,
        'query_category': category,
        'book_list': books
    }
    return render(request, 'management/book_list.html', context)

# 详情
@login_required
def book_detail(request, book_id=1):
    user = request.user
    #average_rating = comments.aggregate(Avg('rating'))['rating__avg'] or 0  # 计算平均评分
    try:
        book = Book.objects.get(pk=book_id) # 根据id返回书籍信息


    except Book.DoesNotExist:
        return HttpResponseRedirect(reverse('book_list', args=('all', )))

    try:
        book_introduction = Intro.objects.get(book=book)
    except Intro.DoesNotExist:
        book_introduction = None

    try:
        comments = Comment.objects.filter(book=book)
        average_rating = comments.aggregate(Avg('rating'))['rating__avg'] or 0  # 计算平均评分
    except Comment.DoesNotExist:
        average_rating=None
    context ={
        'user': user,
        'active_menu': 'view_book',
        'book': book,
        'average_rating': average_rating,
        'book_introduction':book_introduction

    }
    return render(request, 'management/book_detail.html', context)

@login_required
def view_comments(request, book_id):
    book = Book.objects.get(pk=book_id)
    comments = Comment.objects.filter(book=book)
    average_rating = comments.aggregate(Avg('rating'))['rating__avg'] or 0  # Calculate the average rating

    if request.method == 'POST':
        content = request.POST.get('content')
        rating = request.POST.get('rating')
        if content:
            new_comment = Comment.objects.create(book=book, user=request.user,content=content, rating=rating, created_at=timezone.now())
            # 可以根据需要进行其他操作，例如重定向或刷新评论列表
            return redirect('view_comments', book_id=book_id)
    return render(request, 'management/view_comments.html', {'book': book, 'comments': comments,'average_rating': average_rating,})

bookManagement/templates/management/add_book.html
<!--
添加图书：
    设计：
        在两种不同的用户之间做出判断是必要的，而且仅仅只是将普通用户的页面上将管理员权限隐藏是不安全的，
        所以基于用户模型的基础上，要多做出一个判断，即该用户是不是管理员，如果是就返回一个权限表单，反之直接跳转主页
-->
{% extends 'management/base.html' %}
{% block title %}添加图书{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
                {% if state == 'success' %}
                <div class="well">
                    <h2 class="text-success text-center">添加成功</h2>
                </div>
                {% endif %}
                <form method="post" role="form" class="form-horizontal">
                    {% csrf_token %}
                    <h1 class="form-signin-heading text-center">添加图书</h1>
                    <div class="form-group">
                        <label for="id_name" class="col-md-3 custom-control-label">书名：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control"
                                   id="id_name" required name="name" autofocus>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_author" class="col-md-3 custom-control-label">作者：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control"
                            required name="author" id="id_author">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_category" class="col-md-3 custom-control-label">类型：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control"
                            required name="category" id="id_category">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_price" class="col-md-3 custom-control-label">价格：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control"
                            required name="price" id="id_price">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_pubdate" class="col-md-3 custom-control-label">出版日期：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control"
                            required name="publish_date" id="id_pubdate">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-4 col-md-offset-4">
                            <button class="btn btn btn-primary btn-block" type="submit">提交</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

bookManagement/templates/management/add_img.html
<!--
添加图片：
    设计：
        pass
    细明：
        添加了enctype，使后端接收到前端上传到的文件
-->
{% extends 'management/base.html' %}
{% block title %}添加图书图片{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
                {% if state == 'success' %}
                <div class="well">
                    <h2 class="text-success text-center">添加成功</h2>
                </div>
                {% elif state == 'error' %}
                <div class="well">
                    <h2 class="text-danger text-center">添加失败</h2>
                </div>
                {% endif %}
                <form method="post" role="form" class="form-horizontal" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h1 class="form-signin-heading text-center">添加图片</h1>
                    <div class="form-group">
                        <label for="id_name" class="col-md-3 custom-control-label">名称：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control"
                                   id="id_name" required name="name" autofocus>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_discription" class="col-md-3 custom-control-label">描述：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control"
                            required name="description" id="id_discription">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_book" class="col-md-3 custom-control-label">所属书籍：</label>
                        <div class="col-md-9">
                            <select name="book" id="id_book" class="form-control">
                                {% for book in book_list %}
                                <option value="{{ book.id }}">{{ book.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="di_img" class="col-md-3 custom-control-label">图片：</label>
                        <div class="col-md-9">
                            <input type="file" id="id_img" name="img"
                                   class="form-control" accept=".png, .jpg" required>


{#                            <input type="text" class="newtext" value="选择文件"/>#}
{#                            <button class="change_btn">选择文件</button>#}
{#                            <script type="text/javascript">#}
{#                                $(".change_btn").click(function () { $(".filess").click(); });#}
{#                                     $('.filess').change(function(){#}
{#                                     var file=$('.filess').val();#}
{#                                     $('.newtext').val(file);#}
{#                                 })#}
{#                            </script>#}


                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-4 col-md-offset-4">
                            <button class="btn btn btn-primary btn-block" type="submit">提交</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

bookManagement/templates/management/add_intro.html
{% extends 'management/base.html' %}
{% block title %}添加书籍简介{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
                {% if state == 'success' %}
                <div class="well">
                    <h2 class="text-success text-center">添加成功</h2>
                </div>
                {% elif state == 'error' %}
                <div class="well">
                    <h2 class="text-danger text-center">添加失败</h2>
                </div>
                {% endif %}
                <form method="post" role="form" class="form-horizontal" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h1 class="form-signin-heading text-center">添加简介</h1>
<!--                    <div class="form-group">-->
<!--                        <label for="id_name" class="col-md-3 custom-control-label">名称：</label>-->
<!--                        <div class="col-md-9">-->
<!--                            <input type="text" class="form-control"-->
<!--                                   id="id_name" required name="name" autofocus>-->
<!--                        </div>-->
<!--                    </div>-->

                    <div class="form-group">
                        <label for="id_introduction" class="col-md-3 custom-control-label">简介：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control"
                            required name="introduction" id="id_introduction">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_book" class="col-md-3 custom-control-label">所属书籍：</label>
                        <div class="col-md-9">
                            <select name="book" id="id_book" class="form-control">
                                {% for book in book_list %}
                                <option value="{{ book.id }}">{{ book.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

<!--                    <div class="form-group">-->
<!--                        <label for="di_img" class="col-md-3 custom-control-label">图片：</label>-->
<!--                        <div class="col-md-9">-->
<!--                            <input type="file" id="id_img" name="img"-->
<!--                                   class="form-control" accept=".png, .jpg" required>-->


<!--{#                            <input type="text" class="newtext" value="选择文件"/>#}-->
<!--{#                            <button class="change_btn">选择文件</button>#}-->
<!--{#                            <script type="text/javascript">#}-->
<!--{#                                $(".change_btn").click(function () { $(".filess").click(); });#}-->
<!--{#                                     $('.filess').change(function(){#}-->
<!--{#                                     var file=$('.filess').val();#}-->
<!--{#                                     $('.newtext').val(file);#}-->
<!--{#                                 })#}-->
<!--{#                            </script>#}-->


<!--                        </div>-->
<!--                    </div>-->

                    <div class="form-group">
                        <div class="col-md-4 col-md-offset-4">
                            <button class="btn btn btn-primary btn-block" type="submit">提交</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

bookManagement/templates/management/book_detail.html
{% extends 'management/base.html' %}
{% block title %}查看图书{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="col-md-5">
                    {% if book.image_set.all%}
                        <div id="carousel-generic" class="carousel slide" data-ride="carousel">
<!--                            <ol class="carousel-indicators">-->
<!--                                {% for img in book.image_set.all %}-->
<!--                                    <li data-target="#carousel-generic" data-slide-to="'{{ forloop.counter0 }}">-->
<!--                                    {% if forloop.first %} class="active"{% endif %}-->
<!--                                    </li>-->
<!--                                {% endfor %}-->
<!--                            </ol>-->
                            <div class="carousel-inner" role="listbox">
                                {% for img in book.image_set.all %}
                                    <div {% if forloop.first %} class="item active" {% else %} class="item"{% endif %}>
                                        <img class="img-fluid" src="{{ img.img.url }}">
                                    </div>
                                {% endfor %}
                            </div>
                            <a class="left carousel-control-next" href="#carousel-generic" role="button" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                            </a>
                        </div>
                    {% else %}
                        <p class="text-center">暂无图片</p>
                    {% endif%}
                    <hr>
                    <!-- 添加评论按钮 -->
                    <a href="{% url 'view_comments' book.id %}" class="btn btn-primary">查看评论</a>
                </div>
                <div class="col-md-6 col-md-offset-1">
                    <h2 class="text-center">{{ book.name }}</h2>
                    <hr>
                    <h3>作者: {{ book.author }}</h3>
                    <h3>类别: {{ book.category }}</h3>
                    <h3>出版日期: {{ book.publish_date|date:"Y-m-d" }}</h3>
                    <h3>价格: {{ book.price|floatformat:2 }}</h3>
                    <hr>
<!--                    <h3>简介:</h3>-->
<!--                    <p>{{ book_description.description }}</p>-->
                     <h3>简介:</h3>
                    {% if book_introduction %}
                        <p>{{ book_introduction.introduction }}</p>
                    {% else %}
                        <p>暂无简介</p>
                    {% endif %}
                    <hr>
                     <!-- 显示推荐指数 -->
                    <h3>推荐指数：</h3>
                    <div class="fixed-rating">
                        {% for star in "12345" %}
                            {% if average_rating >= star|add:0 %}
                                <span class="fa fa-star" style="color:orange;"></span>
                            {% else %}
                                <span class="fa fa-star" style="color:grey;"></span>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <p>{{ average_rating|floatformat:1 }} / 5.0</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

bookManagement/templates/management/book_list.html
<!--
图书列表：
    图书列表
    分页
    筛选

    明细：
        在设计之初，最容易想到的产生一个列表的办法是：从数据库中直接提取所有数据（.all），
    但带来的麻烦是数据量大后效率低下，所以可以采用使用其中一个字段来回收其他数据（.values/.values_list）
        对于分页和筛选是较为容易的，可以直接切片和使用filter()
-->
{% extends 'management/base.html' %}
{% block title %}查看图书{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="col-md-2">
                    <div class="list-group">
                        <a href="{% url 'book_list' 'all' %}" class="list-group-item"
                           id="id_category_all">全部图书</a>
                        {% for category in category_list %}
                        <a href="{% url 'book_list' category %}"
                           class="list-group-item"
                           id="id_category_{{ category }}">{{ category }}</a>
                        {% endfor %}
                    </div>
                    <script type="text/javascript">
                        $('#id_category_{{ query_category }}').addClass('active');
                    </script>
                </div>
                <div class="col-md-9 col-md-offset-1">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>书名</th>
                            <th>作者</th>
                            <th>出版日期</th>
                            <th>定价</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for book in book_list %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td><a href="{% url 'book_detail' book.id %}">{{ book.name }}</a></td>
                            <td>{{ book.author }}</td>
                            <td>{{ book.publish_date|date:'Y-m-d' }}</td>
                            <td>{{ book.price|floatformat:2 }}</td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td>暂无图书</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <nav>
                        <ul class="pager">
                            {% if book_list.has_previous %}
                            <li class="calendarnav-previous">
                                <a href="{% url 'book_list' query_category %}?page={{ book_list.previous_page_number }}">上一页</a>
                            </li>
                            {% else %}
                            <li class="previous disabled"><a href="#">上一页</a></li>
                            {% endif %}
                            第{{ book_list.number }} / {{ book_list.paginator.num_page }}页
                            {% if book_list.has_next %}
                            <li class="next">
                                <a href="{% url 'book_list' query_category %}?page={{ book_list.next_page_number }}">下一页</a>
                            </li>
                            {% else %}
                            <li class="next disabled"><a href="#">下一页</a></li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
{% endblock %}